### PR TITLE
Issue 65

### PR DESCRIPTION
**Pull request by alexeyzab**
Hi there!

I wanted to try and find something new for the CFP section, since the issues mentioned before seem to be a bit stale. I am not sure if it's better to repeat them again or give up. I tried looking for more recent and more approachable issues by using the [Hackage's top downloaded packages](https://hackage.haskell.org/packages/top) page. Also, it seems like there is a [new issue](https://github.com/dmjio/miso/issues/181#issuecomment-317306170) on `miso` that is a better fit than the one I added last time.

### CODE REVIEW

**Comment by alexeyzab** [comment]
Yeah, that's understandable. It's a shame, I was hoping we'd be able to emulate what the Rust community is doing, but I guess the situation here is too different.

In any case, I am up for helping in any way.

**Comment by tfausak** [comment]
It's only been two weeks, so I'm not quite ready to give up on it. But the initial response has been underwhelming.

**Comment by tfausak** [comment]
> I don't have the numbers handy

I do now. I the latest issue (64), the most popular link got 174 clicks. The least popular featured link got 35 clicks. *All* five of the CFP links together got 40 clicks total. So, not hopelessly dire, but not great.

**Comment by tfausak** [comment]
👉 #83

**Comment by simonmichael** [comment]
I learned about Haskell Weekly's Call for participation section today, when hledger got a new contributor thanks to being mentioned there. Great! Thanks! This is valuable! I would submit new link(s) there each issue if it were allowed. :)

**Comment by tfausak** [comment]
I'm happy to hear it! Submitting links (everywhere, not just the CFP section) is not only allowed, it's encouraged!

**Pull request merged**
