### PR TITLE
Issue 83

### PR DESCRIPTION
**Pull request by tfausak**

### CODE REVIEW

**Comment by tfausak** [comment]
Thanks for doing the CFP issues! Is there any way we can incorporate [24 Pull Requests](https://24pullrequests.com/)?

**Comment by alexeyzab** [comment]
Hm, do you mean mentioning it as a source of Haskell projects to contribute to or something more specific?

**Comment by tfausak** [comment]
I think a simple call out like the one for Hacktoberfest in [issue 77](https://haskellweekly.news/issues/77.html) would be fine.

**Comment by alexeyzab** [comment]
Maybe something along the lines of: "Check out [24 Pull Request](https://24pullrequests.com/languages/haskell) for some additional Haskell projects to work on!"?

**Comment by alexeyzab** [comment]
Good idea btw! :+1:

**Pull request merged**
