### PR TITLE
2017 survey

### LINKED ISSUE #102: Survey
I recently saw the Rust survey results: https://blog.rust-lang.org/2017/09/05/Rust-2017-Survey-Results.html

I know of a few Haskell surveys from the past:

- http://blog.johantibell.com/2010/08/results-from-state-of-haskell-2010.html
- http://blog.johantibell.com/2011/08/results-from-state-of-haskell-2011.html
- https://www.fpcomplete.com/blog/2015/05/thousand-user-haskell-survey

There may be more, but I don't know about them.

The previous Haskell surveys didn't get as many responses as the latest Rust survey:

Survey | Responses
--- | ---
Rust 2017 | 5 368
Haskell 2015 | 1 240
Haskell 2011 | 798
Haskell 2010 | 804

Regardless, I think it would be good to survey the Haskell community. Probably on a yearly basis. Seeing as I run Haskell Weekly, it makes sense to me to send the survey out through Haskell Weekly. I don't yet know what I want the survey to look like or when it should go out. That's what this issue is for 😄

### PR DESCRIPTION
**Pull request by tfausak**
This fixes #102.

### CODE REVIEW

**Comment by tfausak** [comment]
I started converting the form I mentioned here: https://github.com/haskellweekly/haskellweekly.github.io/issues/102#issuecomment-337952667

Still to do:

- Figure out how to direct people to appropriate questions based on their answers. 
- Make sure Formspree is a reasonable place to send these surveys. 
- Finish copying the questions over from the Google form.
- Add any more questions that might be relevant. 
- Determine a good time to publish this survey.

**Comment by tfausak** [comment]
I think prefixing the questions with guards is fine. Instead of throwing in some JavaScript logic for showing/hiding the question based on previous answers, they'll just say: "If (something), (question)?".

Formspree is a fine service. There are [some alternatives](https://alternativeto.net/software/formspree-io/). For future years, it might be worth paying for an alternative or developing my own. For now, Formspree is free and can be used to see if this is even a good idea.

I finished copying the questions from the Google form. 

The last non-operational thing to do is figure out if any questions need to be added (or removed or changed) from the form. I'm going to solicit feedback from a wider range of folks for that. I know @alexeyzab had some comments in #102; what do you think about how the form looks now, Alexey?

**Comment by tfausak** [comment]
My plan for now is to stealth launch the survey to collect feedback. It's easier to make sense of a web page than raw HTML.

**Comment by alexeyzab** [comment]
@tfausak Good job! Short and to the point, I like it.

A couple of minor things:
* How do you feel about moving the email address form onto a new line?
* Should we add some community-oriented questions? Something like "What would you like to change about Haskell's community? Which resources do you use for participating in the community? (mailing lists, Reddit, fpchat, etc.) If you have contributed to open source Haskell projects before, how easy was it for you to get involved?"
* Also, Haskell proficiency questions like "How would you rate your Haskell proficiency level?" And somewhat related to that: "What kind of content do you want to see when it comes to Haskell news and blog posts?". I remember hearing a while back that there weren't that many intermediate level Haskell resources, it'd be nice to know what kind of things people would like to see.

**Comment by tfausak** [comment]
Those all sound good to me. I'll note them over in #102.

**Pull request merged**
