### PR TITLE
Issue 94

### PR DESCRIPTION
**Pull request by tfausak**

### CODE REVIEW

**Comment by madgen** [comment]
Slightly late self-plug: https://dodisturb.me/posts/2018-01-28-Cellular-Christmas-Tree.html

**Comment by tfausak** [comment]
Ah, sorry I missed your post! I'll be sure to include it in this issue.

**Comment by tfausak** [comment]
This issue should include a link to the [Humble Book Bundle: Functional Programming](https://www.humblebundle.com/books/functional-programming-books), which includes a couple Haskell books. Indie Kings, of all people, tipped me off [on Twitter](https://twitter.com/IndieKings/status/963130747241381888).

**Comment by owickstrom** [comment]
Not sure if you got it through the feed, but the last domain modelling video might be interesting to include: https://haskell-at-work.com/episodes/2018-02-11-domain-modelling-with-haskell-factoring-out-recursion.html

**Comment by tfausak** [comment]
Thanks for the heads up! I don't remember where exactly I saw it, but I did see it 😄 I'll be sure to include it in this issue!

**Comment by tfausak** [comment]
Thank you so much for the contributions, @madgen, @sumidiot, @owickstrom, and @vertexcite!

**Comment by madgen** [comment]
Thank you for including!

**Comment by vertexcite** [comment]
Thanks for including it, and thank you for these weekly updates, always so interesting!

**Pull request merged**
