### PR TITLE
Issue 90

### PR DESCRIPTION
**Pull request by tfausak**

### CODE REVIEW

**Comment by markus1189** [comment]
Shameless self plug: https://www.meetup.com/Frankfurt-Haskell-User-Group/events/245856570/

:smile:

**Comment by tfausak** [comment]
Thanks! I'll be sure to include that in this issue.

**Comment by owickstrom** [comment]
Another self-plug: https://coda.wickstrom.tech/episodes/2018-01-13-dynamic-test-suites-in-haskell-using-hspec-and-tasty.html 😄

**Comment by tfausak** [comment]
Great! We love self plugs. I'll be sure to include that too.

**Comment by tfausak** [comment]
Thanks for the contributions, @markus1189 & @owickstrom!

**Pull request merged**
