### PR TITLE
Issue 68

### PR DESCRIPTION
**Pull request by tfausak**
http://conf.researchr.org/home/icfp-2017
http://taylor.fausak.me/2017/08/09/deriving-type-classes-in-haskell-is-slow/
http://vaibhavsagar.com/blog/2017/08/13/i-haskell-a-git/
http://www.michaelburge.us/2017/08/15/how-do-i-modify-a-variable-in-haskell.html
https://blog.eta-lang.org/the-best-of-both-the-worlds-eta-and-java-part-3-4100a1e4b96d
https://blog.qfpl.io/posts/fp-cheat-sheet/
https://flatris.haskell-miso.org/
https://gergo.erdi.hu/projects/icfp-bingo-2017/
https://gist.github.com/chrisdone/6b99d27f666aeea71cc532d2543a6901
https://github.com/ChrisPenner/selections
https://github.com/jonascarpay/apecs
https://github.com/lucasdicioccio/http2-client
https://github.com/rodrigosetti/master-plan
https://hookrace.net/blog/time.gif/
https://itu.dk/people/asal/pubs/msc-thesis-report.pdf
https://jeltsch.wordpress.com/2017/08/14/haskell-in-leipzig-2017-submission-deadline-ahead/
https://jship.github.io/posts/2017-08-14-writing-performant-haskell-part-5.html
https://lexi-lambda.github.io/blog/2017/08/12/user-programmable-infix-operators-in-racket/
https://m0ar.github.io/safe-streaming/2017/08/11/usability-implications-of-linearity.html
https://markkarpov.com/post/announcing-hasky-stack.html
https://michael.steindorfer.name/publications/phd-thesis-efficient-immutable-collections.pdf
https://mmhaskell.com/blog/2017/8/14/starting-out-with-haskell-tensor-flow
https://vadosware.io/post/end-to-end-testing-with-hspec-almost/
https://www.meetup.com/Berlin-Functional-Programming-Group/events/242559370/
https://www.twilio.com/blog/2017/08/build-a-reddit-slack-bot-in-haskell.html

### CODE REVIEW

**Comment by tfausak** [comment]
@alexeyzab are you interested in editing this issue? I'm out of town with no laptop, which makes it hard (but not impossible). I've already compiled a bunch of links, all you would need to do is pick 10 to feature (the Twilio post should be one of them) and find pull quotes for them. 

If you don't want to or can't do it, it's no problem.

**Comment by alexeyzab** [comment]
@tfausak Sure thing! Do I need to do any kind of deployment or is it all automatic?

**Comment by tfausak** [comment]
Great, thanks! Just make a PR sometime before 9 AM CT on Thursday. I'll handle the rest (most of it is automatic).

**Comment by alexeyzab** [comment]
Np, here's the PR: https://github.com/haskellweekly/haskellweekly.github.io/pull/96.

**Comment by tfausak** [comment]
Excellent work! There may be some new stuff to add before tomorrow morning, but we don't really need to worry about that. 

The actual email is scheduled to go out at 10 AM CT every Thursday if there is a new post in the RSS/Atom feed. So I'll merge this tomorrow morning sometime to kick that process off. 

I'll also post it to Reddit and announce it on Twitter.

**Comment by alexeyzab** [comment]
Thanks! Sounds good. I'll be around in case there are any last-minute changes needed to be made.

**Pull request merged**
