### PR TITLE
Issue 64

### PR DESCRIPTION
**Pull request by tfausak**

### CODE REVIEW

**Comment by alexeyzab** [comment]
@tfausak Hey there! How's the CFP section this week? I think some of the old ones can be reused if there aren't enough new ones.

**Comment by tfausak** [comment]
I haven't had time to look for issues. Seems like most of last week's are still open, but I saw a few comments on each of them. I may recycle them, pick a couple new ones, or leave the section blank. Not sure.

**Comment by alexeyzab** [comment]
I am guessing nobody has reached out to get their issues posted yet? I can do the recycling part in a separate PR just to have something for this week.

**Comment by tfausak** [comment]
Nope, nobody has reached out.

**Pull request merged**
