### PR TITLE
Improve performance

### LINKED ISSUE #81: CI build is broken
The CI build died twice in a row:

- https://travis-ci.org/haskellweekly/haskellweekly.github.io/builds/255657701
- https://travis-ci.org/haskellweekly/haskellweekly.github.io/builds/255659376

Building simply takes too long (or consumes too much memory) for Travis to handle. I see a couple ways out of this:

- Prune the dependencies. This would be hard because Hakyll eventually depends on Pandoc, which is a beast to build.
- Switch to lighter dependencies. For example, I could get away with using [CMark](https://hackage.haskell.org/package/cmark) instead of Pandoc. This would require writing a little bit of my own code.
- Aggressively remove almost all dependencies. In other words, write my own static site generator. This might be fun but also time consuming. It could also allow me to do some interesting stuff, like representing issues as Haskell data types.
- Switch to GitHub Pages (which uses Jekyll) and avoid building anything myself. This is by far the easiest option since I'm already familiar with Jekyll. The downside is that Haskell Weekly wouldn't be built with Haskell.

### PR DESCRIPTION
**Pull request by tfausak**
This will fix #81. It's still a work in progress.

- This removes almost all dependencies. That means no more Hakyll on Pandoc. 
- I wasn't able to remove all non-boot dependencies. It would be possible to avoid cmark by writing the issues in HTML, but I don't think that's worth it. Both text and cmark build pretty quickly. 
- To avoid pulling in a YAML parser I switched from YAML front matter to an HTML comment. That's why all the `content/issues/*.markdown` files changed. 
- I rolled my own (probably terrible) template engine. It only supports simple substitutions delimited by dollar signs. 
- I haven't sanity checked the output for good Unicode support, smart quotes, and stuff like that. 
- The Atom and XML feeds don't exist yet. 
- The actual code is pretty gross. It's a first pass. 

In spite of all that, it appears to work and builds super fast. We'll see what CI says.

### CODE REVIEW

**Comment by tfausak** [comment]
Less than 10 minutes from scratch isn't too bad. That includes installing GHC.

**Comment by tfausak** [comment]
Hmm, 4 minutes with a warm cache isn't quite as good as I was expecting. None of the groups of lines in the build log have a time higher than 20 seconds, so it must be restoring the cache or something. I think that Travis has images for GHC 7.8; if I was able to use that I might get even better build times.

**Comment by tfausak** [comment]
I think 2 minutes with a warm cache is about as good as it gets. That's how long [a Jekyll build](https://travis-ci.org/tfausak/tfausak.github.io/builds/257506014) takes. Overall I think this is ready to go. It takes a cold cache build from more than 50 minutes to about 10 minutes; a warm cache from 8 minutes to 2. 

I made a couple changes to the output, but by and large everything should be the same. Obviously my home grown static site generator doesn't have as many features as Hakyll, but it was surprisingly easy to put together. The flow for making new issues hasn't changed at all, so that's good.

**Comment by jgm** [comment]
> I rolled my own (probably terrible) template engine. It only supports simple substitutions delimited by dollar signs.

Why not use doctemplates, pandoc's templating engine, which is available as a separate package?

**Comment by tfausak** [comment]
I didn't know about doctemplates! It looks like the good version of what I ended up with. I'm sure building it is fast enough, but I ended up with only two dependencies (cmark and text). Depending on doctemplates would drag in at least 7 (non-builtin) dependencies. 

I think if I was going to bring a templating package in, it would probably be [template](https://hackage.haskell.org/package/template). But what I've got works pretty well for now.

**Pull request merged**
